modify proxmox

diff --git a/ProxmoxVE/Dockerfile b/ProxmoxVE/Dockerfile
--- a/ProxmoxVE/Dockerfile
+++ b/ProxmoxVE/Dockerfile
@@ -6,13 +6,17 @@ RUN sed -i 's|^deb http://ftp.debian.org|deb https://mirrors.ustc.edu.cn|g' /etc
     sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&\
     sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list
 RUN echo "root:root"|chpasswd &&\
+    echo "deb http://mirrors.ustc.edu.cn/proxmox/debian/pve bullseye pve-no-subscription" > /etc/apt/sources.list.d/pve-no-subscription.list &&\
+    wget http://mirrors.ustc.edu.cn/proxmox/debian/proxmox-release-bullseye.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg &&\
     apt update &&\
-    apt install -y --no-install-recommends ca-certificates wget curl screen vim systemctl && \
-    #主要是ca-certificates
-    echo "deb https://mirrors.ustc.edu.cn/proxmox/debian/pve bullseye pve-no-subscription" > /etc/apt/sources.list.d/pve-no-subscription.list &&\
-    wget https://mirrors.ustc.edu.cn/proxmox/debian/proxmox-release-bullseye.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg &&\
-    apt update && \
-    #repacked proxmox-ve
+    apt install -y --no-install-recommends ca-certificates wget curl screen vim systemctl busybox && \
+    busybox --install &&\
+    #intall proxmox-ve without recommends. ifupdown2 will install failed but ok
+    apt-get -y --no-install-recommends  install  proxmox-ve=7.2-1 || echo ok && \
+    #clean
+    apt-get clean &&\
+    rm -rf /var/lib/apt/lists/*
+RUN #repacked proxmox-ve \
     wget https://mirrors.ustc.edu.cn/proxmox/debian/dists/bullseye/pve-no-subscription/binary-amd64/proxmox-ve_7.2-1_all.deb && \
     mkdir /tmp/pve && \
     dpkg -X proxmox-ve_7.2-1_all.deb /tmp/pve/ && \
@@ -27,13 +31,9 @@ RUN echo "root:root"|chpasswd &&\
     dpkg -e pve-manager_7.2-7_amd64.deb /tmp/pve-manager/DEBIAN && \
     sed -i "s/ifupdown2 (>= 2.0.1-1+pve8) | ifenslave (>= 2.6),//g" /tmp/pve-manager/DEBIAN/control && \
     dpkg-deb -Zxz  -b /tmp/pve-manager/ /tmp &&\
-    #intall proxmox-ve without recommends. ifupdown2 will install failed but ok
-    apt-get -y --no-install-recommends  install  proxmox-ve=7.2-1 || echo ok && \
     ##install again
     dpkg -i /tmp/*.deb || echo ok &&\
-    #clean
-    apt-get clean &&\
-    rm -rf /var/lib/apt/lists/* /*.deb /tmp/*
+    rm -rf /*.deb /tmp/*
 
 STOPSIGNAL SIGINT
 CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target"]
